---
title: "MAST90083 Assignment 1"
author: "Haonan Zhong"
date: '2022-08-29'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Question 1.1
```{r}
library("MASS")
library("ISLR")
library("glmnet")
data(Hitters)
# Remove rows with NA in the Salary column
Hitters <- Hitters[!is.na(Hitters$Salary),]
```

### Question 1.2
```{r}
# Construct design matrix and response variable
x <- model.matrix(~.-1, data = subset(Hitters, select = -(Salary)))
y <- Hitters$Salary
lambda <- 10^seq(10, -2, length = 100)

# Estimate ridge coefficients for 100 lambda values
coef_estimate <- glmnet(x, y, alpha = 0, lambda = lambda)
# Observe the coefficents for the largest lambda
coef(coef_estimate)[,1]
#Observe the coefficients for the smallest lambda
coef(coef_estimate)[,100]
```
As we can see from the output above, coefficients for the largest lambda is much more closer to 0. Which is quite reasonable, as the impact of shrinkage penalty grows as $\lambda$ increases, and the ridge regression coefficients will get closer to 0.

### Question 1.3
```{r}

```
